config/routes.rb
Rails.application.routes.draw do
  resources :searchs, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/search_result.rb
class SearchResult < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def create
    @search_service = SearchService.new(params[:q])
    @search_service.call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Stack Search" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="<%= asset_url("dev-search.png") %>" type="image/png">
    <link rel="apple-touch-icon" href="<%= asset_url("dev-search.png") %>">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="w-full min-h-screen bg-gradient-to-b from-black to-indigo-500 flex flex-col items-center justify-center">
  <div class="max-w-5xl w-full mx-auto flex flex-col px-8 lg:px-0">
  <h1 class="text-2xl text-center text-white mb-4"> Search stack overflow easily </h1>
  <p class="text-xl text-center text-gray-100 mb-8"> Find relevent answers to your questions </p>
  <div class="max-w-2xl w-full mx-auto">
    <%= form_with url: searchs_path do |f| %>
      <% f.text_field :q, class: "w-full bg-transparent outline-none border-0 border-b-2 border-white text-white text-xl 
        focus:outline-none focus:ring-0
        placeholder-indigo-100 p-2",
        placeholder: "Enter your search content" %>
    <% end %>
  </div>
  <p class="mt-16 text-white"> Official search pages </p>
  <div class="mt-4 flex gap-8 items-center flex-wrap">
    <%= link_to "Github Search", "https://github.com/search", target: "_new", class: "bg-indigo-500 text-indigo-50 px-3 py-2 rounded-full hover:bg-blue-700 text-nowrap" %>
    <%= link_to "Stack overflow Search", "https://stackoverflow.com/search", target: "_new", class: "bg-indigo-500 text-indigo-50 px-3 py-2 rounded-full hover:bg-blue-700 text-nowrap" %>
    <%= link_to "Mozilla Dev Docs", "https://developer.mozilla.org/en-US/docs/Web", target: "_new", class: "bg-indigo-500 text-indigo-50 px-3 py-2 rounded-full hover:bg-blue-700 text-nowrap" %>
    <%= link_to "TailwindCSS Docs", "https://tailwindcss.com/", target: "_new", class: "bg-indigo-500 text-indigo-50 px-3 py-2 rounded-full hover:bg-blue-700 text-nowrap" %>
    <%= link_to "Rails Docs", "https://guides.rubyonrails.org/", target: "_new", class: "bg-indigo-500 text-indigo-50 px-3 py-2 rounded-full hover:bg-blue-700 text-nowrap" %>
  </div>
</div>